name: hello-world-cli
version: 0.1
summary: Hello World
description: |
  This demo is intended to show how to build your first snap
  This code is part of the Snapcraft example tour at
  https://developer.ubuntu.com/snapcraft-getting-started

parts:
  hello:
    plugin: cmake
    source: https://github.com/ubuntu-core/snapcraft-examples.git
    source-subdir: 01-hello-world-cli/src

apps:
  hello-world-cli:
    command: hello
